name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Compile
        run: npm run compile
      - name: Publish package
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm config set registry 'https://registry.npmjs.org/'
          npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
          npm publish
